Lisandro
sebapderbeck/algoritmos_tp1_pokemon pull request #4
Opened 2019-07-27 02:01 UTC by lisandromar

Definido el struct del array de pokemones.
Ordenar los pokemones por tipo.
Dado el promedio de niveles de pokemones por tipo.

2019-07-29 14:20 UTC, sebapderbeck requested changes

2019-07-29 14:20 UTC, sebapderbeck commented on functions/Menu_controller.cpp
> +int getLimitPokemonInArray(); // pide al usuario un limite de pokemones para ingresar
esta funcion no se usa

2019-07-29 14:20 UTC, sebapderbeck commented on functions/Menu_controller.cpp
> +void promedioNivelPorTipo(tPokemon rPokemon[], int current_register_length); //calcula el promedio de niveles por tipo
el nombre de las funciones deberia estar en ingles

2019-07-29 14:20 UTC, sebapderbeck commented on functions/Menu_controller.cpp
> +    tPokemon rPokemon[802];
deberiamos poner el limite que dijo el profesor

2019-07-29 14:20 UTC, sebapderbeck commented on functions/Menu_controller.cpp
> +int getLimitPokemonInArray(){
eliminaria esta funcion

2019-07-29 14:20 UTC, sebapderbeck commented on functions/Menu_controller.cpp
> +    int contador_fuego = 0;
unificaria la asignacion de todas estas variables para ocupar una sola linea

2019-07-29 14:20 UTC, sebapderbeck commented on functions/Menu_controller.cpp
> +            contador_electrico++;
En varios lugares se calcula el total de pokemones de cada tipo, realizaria una funcion para unificar esto y llamarla cuando sea necesario

2019-07-29 14:20 UTC, sebapderbeck commented on functions/Menu_controller.cpp
> +    int contador_electrico = 0;
unificar asignaciones

2019-07-29 14:20 UTC, sebapderbeck commented on functions/Menu_controller.cpp
> +    gotoxy (32 , 26);
buscaria la forma de unificar la forma en la cual se imprimen los valores de las funciones resultantes. asi ahorramos lineas de codigo y hacemos que el programa se vea mas compacto.
por ejemplo en varios lugares se muestra a los pokemones divididos por tipo, unificaria estas vistas y agregaria un header para identificar cada funcion

2019-07-29 14:20 UTC, sebapderbeck commented on functions/Menu_controller.cpp
> +    cout << " EL PROMEDIO DE NIVELES DE POKEMONES TIPO ELECTRICO ES: " << promedio_electrico;
por ejemplo
||PROMEDIO DE NIVELES DE POKEMONES ||
TIERRA:
FUEGO:
AGUA: 
ELECTRICO :
intentaria hacer algo asi pero mas lindo

2019-07-29 14:20 UTC, sebapderbeck commented on functions/Menu_controller.cpp
> +        if (rPokemon[i].type == "t"){
el if deberia estar preguntando por la letra en mayuscula, ya que utilizamos una funcion para validar las letras y otra para tranformarla a uppercase

2019-07-29 14:20 UTC, sebapderbeck commented on functions/Menu_controller.cpp
> +    cin >> rPokemon[current_register_length].type;
falta validacion del tipo

2019-07-29 14:20 UTC, sebapderbeck commented on functions/Menu_controller.cpp
> +    cin >> rPokemon[current_register_length].level;
falta validacion del nivel

2019-07-29 14:20 UTC, sebapderbeck commented on functions/Menu_controller.cpp
> +    cin >> rPokemon[current_register_length].name;
falta validacion de nombre

2019-07-29 14:20 UTC, sebapderbeck commented on functions/Menu_controller.cpp
> +string ShowTemplateToEnterNameFromFile() {
falta agregar esta funcion y algunas otras al archivo de funciones (donde se explica que hace cada funcion)

2019-08-01 13:46 UTC, lisandromar commented on functions/Menu_controller.cpp
> +int getLimitPokemonInArray(); // pide al usuario un limite de pokemones para ingresar
La saco, no es necesaria por el limite que dijo el profe.

2019-08-04 20:41 UTC, closed without merging